# Server
server.port=8088

# Database (SQLite)
spring.datasource.url=jdbc:sqlite:gestion_affectations.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# JWT Secret (for development, to be externalized in prod)
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expirationMs=86400000
